
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: lock_checker_development
  password: password

test:
  <<: *default
  database: lock_checker_test
  password: password

production:
  <<: *default
  database: lock_checker_production
  username: lock_checker
  password: <%= ENV['DATABASE_URL'] %>
